- job:
    name: python-novaclient-functional
    parent: devstack-tox-functional
    timeout: 7200
    required-projects:
      - openstack/nova
      - openstack/python-novaclient
    vars:
      openrc_enable_export: true
      devstack_localrc:
        KEYSTONE_ADMIN_ENDPOINT: true
        NEUTRON_ENFORCE_SCOPE: false
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-novaclient-functional
    gate:
      jobs:
        - python-novaclient-functional
