- job:
    name: python-novaclient-functional
    parent: devstack
    run: playbooks/python-novaclient-functional.yaml
    post-run: playbooks/post.yaml
    timeout: 7200
    required-projects:
      - openstack/nova
      - openstack/python-novaclient
    vars:
      devstack_localrc:
        USE_PYTHON3: true
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-novaclient-functional
    gate:
      jobs:
        - python-novaclient-functional
